robot_parameters:
    width: 0.1
    base_height: 2.0
    base_mass: 100.0
    axle_offset: 0.05
    rod_length: 1.0
    rod_radius: 0.03
    rod_mass: 1.0
    ball_radius: 0.05
    ball_mass: 0.5
    max_angular_velocity: 6.28318530718  # 2 * pi rad/s
    max_effort: 10.0

