robot_parameters:
    width: 0.2
    base_height: 0.5
    base_mass: 100.0
    axle_offset: 0.05
    rod_length: 0.3
    rod_radius: 0.05
    rod_mass: 1.0
    ball_radius: 0.03
    ball_mass: 0.5
    max_angular_velocity: 0.3
    max_effort: 5.0

